var mochila = []
console.log(mochila)
mochila.push('faca')
mochila.push('pedra')
mochila.push('corda')
mochila.push('lanterna')
console.log(mochila)
mochila.unshift('tênis')
console.log(mochila)
mochila.splice(2, 2)
console.log(mochila)
mochila.push('sardinha', 'garrafa de água')
console.log(mochila)
mochila.sort()
console.log(mochila)
mochila.reverse()
console.log(mochila)
